### ISSUE TITLE
typescript example doesn't work properly

### ISSUE THREAD

**Issue by vojtech-cerveny** [reallymello/nightwatchTutorials#101]
Hey, I am trying to run nightwatch with typescript and I want to have full support of types from nightwatch.

I checked your youtube [video](https://www.youtube.com/watch?v=fUPwk8bFVJM) and I am not sure how it should work.

On line 
https://github.com/reallymello/nightwatchTutorials/blob/master/pomTypeScriptExample/src/tests/googleTest.ts

When I am trying `google.elements` - I am expecting, that I will get elements from PageObject - not intelisense doesn't suggest anything. 

<img width="378" alt="image" src="https://github.com/reallymello/nightwatchTutorials/assets/12935892/3e612b4e-b7ea-47c2-8d0e-a26690650bea">

^^ nothing is suggested (autocomplete is from Co-Pilot)

Can you give me hint how to get elements from `google pageObject` please?

**Comment by reallymello** [comment]
This example should still work if you use `npm install` from the `pomTypeScriptExample\` folder first. There are many tutorials as separate projects in the repository so make sure you change into that directory first so that the correct versions of things are downloaded.

That being said this is an older example and things are even better now in the newer versions so I'll post an updated example using the latest Nightwatch shortly. The biggest different is not needing to transpile the .ts files into .js files to use them.

**Comment by reallymello** [comment]
I added an example using the latest Nightwatch 3.4.1 to [](https://github.com/reallymello/nightwatchTutorials/tree/master/pomTypescriptExample3.4.1)
